[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.121.3",
    "langchain>=1.0.8",
    "langchain-openai>=1.0.3",
    "pydantic>=2.12.4",
    "uvicorn[standard]>=0.38.0",
]
